(function(root){'use strict';
const normalize=s=>String(s??'').normalize('NFKC').toLocaleLowerCase().replace(/[\s\p{P}\p{S}]+/gu,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const platformName=p=>p==='Bilibili'||p==='哔哩哔哩'?'B站':p;
const types=['练习室','镜面','分解教学','编舞视频','翻跳','舞台'];
const regions=['韩流','华语','欧美','日本','其他'];
const extra={'舞台':'live stage 现场 舞台','翻跳':'cover dance 翻跳 舞蹈','练习室':'dance practice 练习 舞蹈 排练','镜面':'mirror mirrored 镜像','分解教学':'tutorial 教程 教学 分解 慢速','编舞视频':'choreography performance 编舞 舞蹈'};
function safeURL(raw){try{const u=new URL(raw);return u.protocol==='https:'&&['www.bilibili.com','bilibili.com','www.youtube.com','youtube.com','www.douyin.com','jingxuan.douyin.com'].includes(u.hostname)?u.href:null}catch{return null}}
function embedURL(raw){const valid=safeURL(raw);if(!valid)return null;const u=new URL(valid);if(u.hostname.includes('bilibili.com')){const id=u.pathname.match(/^\/video\/(BV[a-zA-Z0-9]{10})(?:\/|$)/)?.[1];const aid=u.pathname.match(/^\/video\/av([1-9]\d{0,15})(?:\/|$)/)?.[1];if(!id&&!aid)return null;const page=u.searchParams.get('p')||'1';if(!/^[1-9]\d{0,3}$/.test(page))return null;return 'https://player.bilibili.com/player.html?'+(id?'bvid='+id:'aid='+aid)+'&p='+page+'&autoplay=0&danmaku=0'}if(u.hostname==='www.youtube.com'||u.hostname==='youtube.com'){const id=u.searchParams.get('v');if(u.pathname!=='/watch'||!id||!/^[-a-zA-Z0-9_]{11}$/.test(id))return null;return 'https://www.youtube-nocookie.com/embed/'+id+'?autoplay=0&playsinline=1&rel=0'}return null}
function groupVideos(entries){const map=new Map();for(const e of entries){if(!safeURL(e.url)||!e.song||!e.artist)continue;const key=normalize(e.artist)+'-'+normalize(e.song);if(!map.has(key))map.set(key,{id:key,song:e.song,artist:e.artist,aliases:[],sources:[],cover:null,coverSource:null});const g=map.get(key);g.aliases=[...new Set([...g.aliases,...(e.aliases||[])])];if(!g.sources.some(v=>v.url===e.url))g.sources.push({...e,platform:platformName(e.platform)});if(e.localThumbnail&&!g.cover){g.cover=e.localThumbnail;g.coverSource=e.url}else if(e.thumbnail&&!g.cover){g.cover=e.thumbnail;g.coverSource=e.url}}return [...map.values()]}
function matches(group,state){const tokens=String(state.query||'').trim().split(/\s+/).map(normalize).filter(Boolean);const common=[group.song,group.artist,...group.aliases].join(' ');return group.sources.filter(v=>(!state.region||(v.region||'韩流')===state.region)&&(!state.artist||group.artist===state.artist)&&(!state.type||v.type===state.type)&&(!state.platform||v.platform===state.platform)&&tokens.every(t=>normalize([common,v.title,v.type,extra[v.type]||'',v.platform,v.uploader].join(' ')).includes(t)))}
function results(groups,state){return groups.map(g=>({...g,matched:matches(g,state)})).filter(g=>g.matched.length)}
function externalLinks(q){const text=String(q||'流行歌曲').trim().slice(0,160)+' 舞蹈 练习室';return [{name:'B站搜索',url:'https://search.bilibili.com/all?keyword='+encodeURIComponent(text)},{name:'抖音搜索',url:'https://www.douyin.com/search/'+encodeURIComponent(text)},{name:'YouTube 搜索',url:'https://www.youtube.com/results?search_query='+encodeURIComponent(text)}]}
const api={normalize,groupVideos,matches,results,safeURL,externalLinks,embedURL};if(typeof module==='object'&&module.exports)module.exports=api;if(typeof document==='undefined')return;
const data=root.EIGHTCOUNT_DATA||{videos:[],checkedAt:'',};const groups=groupVideos(data.videos);let state={query:'',type:'',platform:'',artist:'',region:''},lastTrigger=null,composing=false;const $=id=>document.getElementById(id);const songDialog=$('song-dialog'),about=$('about-dialog');
function readLocation(){const p=new URLSearchParams(location.search);state={query:(p.get('q')||'').slice(0,160),type:types.includes(p.get('type'))?p.get('type'):'',platform:['B站','抖音','YouTube'].includes(p.get('platform'))?p.get('platform'):'',artist:groups.some(g=>g.artist===p.get('artist'))?p.get('artist'):'',region:regions.includes(p.get('region'))?p.get('region'):''};$('search').value=state.query}
function syncURL(){const u=new URL(location.href);for(const k of ['q','type','platform','artist','region'])u.searchParams.delete(k);if(state.query.trim())u.searchParams.set('q',state.query.trim());if(state.type)u.searchParams.set('type',state.type);if(state.platform)u.searchParams.set('platform',state.platform);if(state.artist)u.searchParams.set('artist',state.artist);if(state.region)u.searchParams.set('region',state.region);try{history.replaceState(null,'',u)}catch{}}
function option(label,value,kind,count){return '<button type="button" class="filter-option" data-filter="'+kind+'" data-value="'+esc(value)+'" aria-pressed="'+String(state[kind]===value)+'"><span>'+esc(label)+'</span><span>'+count+'</span></button>'}
function renderFilters(){const artists=[...new Set(groups.map(g=>g.artist))].sort((a,b)=>a.localeCompare(b));$('artist-filter').innerHTML='<option value="">全部歌手 / 组合（'+artists.length+'）</option>'+artists.map(a=>'<option value="'+esc(a)+'">'+esc(a)+'</option>').join('');$('artist-filter').value=state.artist||'';const forCount=(kind,value)=>results(groups,{...state,[kind]:value}).length;$('region-filters').innerHTML=option('全部曲库','','region',forCount('region',''))+regions.map(r=>option(r,r,'region',forCount('region',r))).join('');$('type-filters').innerHTML=option('全部类型','','type',forCount('type',''))+types.map(t=>option(t,t,'type',forCount('type',t))).join('');$('platform-filters').innerHTML=option('全部平台','','platform',forCount('platform',''))+['B站','抖音','YouTube'].map(p=>option(p,p,'platform',forCount('platform',p))).join('')}
function card(g,i){const tags=[...new Set(g.matched.map(v=>v.type))],markets=[...new Set(g.matched.map(v=>v.region||'韩流'))],platforms=[...new Set(g.matched.map(v=>v.platform))];const image=g.cover?'<img src="'+esc(g.cover)+'" alt="'+esc(g.artist+' '+g.song+' 视频预览图')+'" loading="lazy" referrerpolicy="no-referrer">':'';const hue=(i*37+80)%360;return '<article class="track-card"><button type="button" class="cover-button" data-song="'+esc(g.id)+'" aria-label="查看 '+esc(g.artist+' '+g.song)+' 的 '+g.matched.length+' 条视频来源"><span class="cover-fallback" style="--hue:'+hue+'"><small>'+esc(g.artist)+'</small><strong>'+esc(g.song)+'</strong></span>'+image+'<span class="cover-overlay"></span><span class="video-count">'+g.matched.length+' 条视频来源</span><span class="play" aria-hidden="true"><svg viewBox="0 0 12 12"><path d="M2 0 12 6 2 12Z"/></svg></span></button><div class="card-head"><button type="button" class="song-title" data-song="'+esc(g.id)+'">'+esc(g.song)+'</button><span class="card-num">'+String(i+1).padStart(2,'0')+'</span></div><p class="artist">'+esc(g.artist)+'</p><div class="tag-row">'+markets.map(r=>'<span class="tag region">'+esc(r)+'</span>').join('')+tags.map(t=>'<span class="tag type">'+esc(t)+'</span>').join('')+platforms.map(p=>'<span class="tag platform">'+esc(p)+'</span>').join('')+'</div></article>'}
function render({url=true}={}){const found=results(groups,state);renderFilters();$('grid').innerHTML=found.map(card).join('');$('grid').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>img.remove(),{once:true}));$('result-count').textContent=found.length+' 首';$('result-heading').firstChild.textContent=state.query.trim()?'搜索结果 ':'练习曲库 ';$('catalog-note').textContent=new Set(groups.map(g=>g.artist)).size+' 位歌手 / 组合 · '+groups.length+' 首曲目 · '+data.videos.length+' 条来源';$('empty').hidden=found.length>0;$('search-status').textContent='找到 '+found.length+' 首歌曲，'+found.reduce((n,g)=>n+g.matched.length,0)+' 条视频来源。';const active=[state.query.trim()?'关键词：'+state.query.trim():'',state.type,state.platform,state.artist,state.region].filter(Boolean);$('active-filter').hidden=!active.length;$('active-filter').textContent=active.join(' · ');$('external-links').innerHTML=externalLinks(state.query).map(x=>'<a href="'+esc(x.url)+'" target="_blank" rel="noopener noreferrer">'+esc(x.name)+'</a>').join('');if(url)syncURL()}
function reset(){state={query:'',type:'',platform:'',artist:'',region:''};$('search').value='';render();$('search').focus()}
function openSong(id,trigger){const g=groups.find(g=>g.id===id);if(!g)return;const matching=matches(g,state);const sources=matching.length?matching:g.sources;lastTrigger=trigger;$('song-detail').innerHTML='<div class="detail-heading"><h2 id="song-dialog-title">'+esc(g.song)+'</h2><p>'+esc(g.artist)+' · '+sources.length+' 条匹配来源</p></div><section id="watch-panel" class="watch-panel" aria-label="站内视频浏览"><div class="watch-placeholder"><span class="eyebrow">WATCH & PRACTICE</span><h3>选一个版本，开始练习</h3><p>点击下方「站内观看」加载原平台播放器。播放器将连接原平台，可能使用其 Cookie；本站不保存视频文件。</p></div></section>'+sources.map(v=>'<article class="source-item"><div class="tag-row"><span class="tag platform">'+esc(v.platform)+'</span><span class="tag type">'+esc(v.type)+'</span></div><h3>'+esc(v.title)+'</h3>'+(v.uploader?'<p class="source-meta">发布账号：'+esc(v.uploader)+'</p>':'')+'<p class="verification">'+esc(v.verificationNote||'已核对来源信息；实际播放以原平台为准。')+'</p><div class="source-actions">'+(embedURL(v.url)?'<button type="button" class="solid-button" aria-pressed="false" data-watch="'+esc(v.url)+'">站内观看</button>':'<span class="embed-unavailable">此来源暂不支持站内播放</span>')+'<a class="source-link" href="'+esc(safeURL(v.url))+'" target="_blank" rel="noopener noreferrer">在'+esc(v.platform)+'看原视频</a></div></article>').join('')+(g.cover?'<p class="image-credit">预览图参考：'+g.sources.filter(v=>v.imageSource).map(v=>'<a href="'+esc(v.imageSource)+'" target="_blank" rel="noopener noreferrer">'+esc(new URL(v.imageSource).hostname)+'</a>').join(' · ')+'</p>':'')+'<p class="detail-notice">原平台可能要求登录或限制地区访问。请尊重原作者，勿将公开可见视为转载授权。</p>';songDialog.showModal();$('song-close').focus()}
function watch(raw,button){const src=embedURL(raw),v=data.videos.find(v=>v.url===raw);if(!src||!v)return;const panel=$('watch-panel');panel.innerHTML='<div class="player-caption"><strong>'+esc(v.title)+'</strong><span>'+esc(v.platform)+' · '+esc(v.uploader||'原发布者')+'</span></div><iframe class="embedded-player" title="'+esc(v.artist+' '+v.song+' 原平台视频播放器')+'" src="'+esc(src)+'" allow="fullscreen; encrypted-media; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe><p class="player-fallback">若播放器提示限制、无法加载或无法播放，请<a href="'+esc(v.url)+'" target="_blank" rel="noopener noreferrer">前往原视频观看</a>。原平台保留播放与广告控制权。</p>';document.querySelectorAll('[data-watch]').forEach(b=>{b.setAttribute('aria-pressed',String(b===button));b.textContent=b===button?'已选择此版本':'站内观看'});panel.scrollIntoView({block:'nearest',behavior:'smooth'})}
function renderPlaylist(){const lists=data.playlists||[];if(!lists.length)return;const list=lists.find(p=>p.id===$('playlist-select').value)||lists[0];$('playlist-status').textContent=list.note||'';$('playlist-tracks').innerHTML=list.tracks.map(t=>{const query=[t.matchArtist||t.artist,t.matchSong||t.song].filter(Boolean).join(' ');const found=results(groups,{query});const label=t.exactMatch===false?'版本待核对':t.versionNote?'有版本说明':found.length?'已有相关舞蹈':'待补舞蹈来源';return '<div class="playlist-track"><span class="playlist-number">'+esc(t.index)+'</span><div><button type="button" data-query="'+esc(query)+'">'+esc(t.song)+'</button><p>'+esc(t.artist||'歌手待确认')+'</p>'+(t.versionNote?'<p class="playlist-version">'+esc(t.versionNote)+'</p>':'')+'</div><span class="playlist-badge">'+esc(label)+'</span></div>'}).join('')}
if((data.playlists||[]).length){$('imported-playlists').hidden=false;$('playlist-summary').textContent=data.playlists.length+' 份 · '+data.playlists.reduce((n,p)=>n+p.tracks.length,0)+' 条歌单记录';$('playlist-select').innerHTML=data.playlists.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.title)+'</option>').join('');$('playlist-select').value=data.playlists[0].id;$('playlist-select').addEventListener('change',renderPlaylist);renderPlaylist()}
$('artist-filter').addEventListener('change',e=>{state.artist=e.target.value;render();$('artist-filter').focus()});
$('search-form').addEventListener('submit',e=>{e.preventDefault();state.query=$('search').value;render()});$('search').addEventListener('compositionstart',()=>composing=true);$('search').addEventListener('compositionend',()=>{composing=false;state.query=$('search').value;render()});$('search').addEventListener('input',()=>{if(!composing){state.query=$('search').value;render()}});
document.addEventListener('click',e=>{const play=e.target.closest('[data-watch]');if(play){watch(play.dataset.watch,play);return}const filter=e.target.closest('[data-filter]');if(filter){const kind=filter.dataset.filter,value=filter.dataset.value;state[kind]=value;render();document.querySelector('[data-filter="'+kind+'"][data-value="'+CSS.escape(value)+'"]')?.focus();return}const quick=e.target.closest('[data-query]');if(quick){if(quick.closest('.playlist-track'))$('imported-playlists').open=false;if(quick.dataset.query==='镜面'){state.query='';state.type='镜面'}else{state.query=quick.dataset.query;state.type='';state.platform='';state.artist='';state.region=''}$('search').value=state.query;render();$('search').focus();return}const track=e.target.closest('[data-song]');if(track)openSong(track.dataset.song,track)});
$('reset').addEventListener('click',reset);$('empty-reset').addEventListener('click',reset);$('song-close').addEventListener('click',()=>songDialog.close());songDialog.addEventListener('close',()=>{$('song-detail').innerHTML='';if(lastTrigger?.isConnected)lastTrigger.focus();else $('search').focus()});$('about-open').addEventListener('click',()=>{about.showModal();$('about-close').focus()});$('about-close').addEventListener('click',()=>about.close());for(const d of [songDialog,about])d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});window.addEventListener('popstate',()=>{if(songDialog.open)songDialog.close();readLocation();render({url:false})});$('verified-date').textContent='来源核对 '+(data.checkedAt||'2026-10-09');readLocation();render({url:false});
const mc=document.modelContext;if(mc?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(mc.registerTool({name:'search_dance_catalog',title:'搜索舞蹈曲库',description:'在已收录的公开视频目录中按歌曲、艺人和类型搜索，并更新页面；不会搜索全网或打开外站。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:160},type:{type:'string',enum:['',...types]},platform:{type:'string',enum:['','B站','抖音','YouTube']}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.query!=='string'||input.query.length>160||Object.keys(input).some(k=>!['query','type','platform'].includes(k))||input.type&&!types.includes(input.type)||input.platform&&!['B站','抖音','YouTube'].includes(input.platform))throw Error('Invalid search input');if(songDialog.open)songDialog.close();state={query:input.query,type:input.type||'',platform:input.platform||'',artist:'',region:''};$('search').value=state.query;render();return results(groups,state).map(g=>({song:g.song,artist:g.artist,videos:g.matched.map(v=>({title:v.title,platform:v.platform,type:v.type,url:v.url}))}))}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}
})(globalThis);
