const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const repoRoot=path.resolve(__dirname,'..');
const staticRoot=fs.existsSync(path.join(repoRoot,'dist','app.js'))?path.join(repoRoot,'dist'):repoRoot;
function setup(playlists){const elements=new Map();class E{constructor(){this.listeners={};this.innerHTML='';this.value='';this.open=false;this.isConnected=true;this.firstChild={textContent:''}}addEventListener(n,f){(this.listeners[n]||=[]).push(f)}fire(n,e={}){for(const f of this.listeners[n]||[])f(e)}insertAdjacentHTML(position,html){assert.equal(position,'beforeend');this.innerHTML+=html}querySelectorAll(){return[]}focus(){this.focused=true}showModal(){this.open=true}close(){this.open=false;this.fire('close')}scrollIntoView(){this.scrolled=true}setAttribute(k,v){this[k]=v}}const get=id=>{if(!elements.has(id))elements.set(id,new E());return elements.get(id)};const doc=new E();doc.getElementById=get;doc.querySelectorAll=()=>[];doc.querySelector=()=>null;const ctx={document:doc,window:new E(),location:{search:'',href:'https://example.test/'},history:{entries:[],replaceState(a,b,u){this.current=String(u)},pushState(a,b,u){this.entries.push(String(u));this.current=String(u)}},URL,URLSearchParams,CSS:{escape:s=>s},AbortController};vm.createContext(ctx);for(const f of ['catalog.js','app.js']){if(f==='app.js'&&playlists)ctx.EIGHTCOUNT_DATA.playlists=playlists;vm.runInContext(fs.readFileSync(path.join(staticRoot,f),'utf8'),ctx);}return {ctx,get,doc,E}}
test('DOM lifecycle: lazy embed, correct player, source attribution, close unload',()=>{const {doc,get,E}=setup();assert.match(get('grid').innerHTML,/How You Like That/);const trigger=new E();trigger.dataset={song:'blackpink-howyoul ikethat'.replaceAll(' ','')};doc.fire('click',{target:{closest:s=>s==='[data-song]'?trigger:null}});assert(get('song-dialog').open);assert(!get('song-detail').innerHTML.includes('<iframe'));assert.match(get('song-detail').innerHTML,/image-credit/);const b=new E();b.dataset={watch:'https://www.youtube.com/watch?v=32si5cfrCNc'};doc.fire('click',{target:{closest:s=>s==='[data-watch]'?b:null}});assert.match(get('watch-panel').innerHTML,/youtube-nocookie.com\/embed\/32si5cfrCNc/);assert.match(get('watch-panel').innerHTML,/strict-origin-when-cross-origin/);assert.match(get('watch-panel').innerHTML,/前往原视频观看/);get('song-dialog').close();assert.equal(get('song-detail').innerHTML,'');assert(trigger.focused)});
test('DOM artist change and reset update results',()=>{const {get}=setup();get('artist-filter').fire('change',{target:{value:'BTS'}});assert.match(get('grid').innerHTML,/Dynamite/);assert(!get('grid').innerHTML.includes('BLACKPINK'));get('reset').fire('click');assert.match(get('grid').innerHTML,/BLACKPINK/);assert.equal(get('artist-filter').value,'')});

test('imported playlist preserves unresolved rows and version caveats safely',()=>{const {get}=setup([{id:'test',title:'测试歌单',note:'已识别3条',tracks:[{index:1,song:'Dynamite',artist:'BTS'},{index:2,song:'Unknown <song>',artist:'Unknown'},{index:3,song:'Dynamite (Remix)',artist:'BTS',matchSong:'Dynamite',versionNote:'仅原曲相关版本，混音待核对',exactMatch:false}]}]);assert.equal(get('imported-playlists').hidden,true);const html=get('playlist-tracks').innerHTML;assert.match(html,/已有相关舞蹈/);assert.match(html,/待补舞蹈来源/);assert.match(html,/版本待核对/);assert.match(html,/Unknown &lt;song&gt;/);assert.equal((html.match(/class="playlist-track"/g)||[]).length,3)});
test('playlist track click closes checklist and filters the catalog',()=>{const {get,doc}=setup();get('imported-playlists').open=true;const quick={dataset:{query:'BTS Dynamite'},closest:s=>s==='.playlist-track'?{}:null};doc.fire('click',{target:{closest:s=>s==='[data-query]'?quick:null}});assert.equal(get('imported-playlists').open,false);assert.match(get('grid').innerHTML,/Dynamite/);assert(!get('grid').innerHTML.includes('BLACKPINK'));assert.equal(get('search').value,'BTS Dynamite')});
test('catalog paginates, more expands, changing query resets limit',()=>{const {get}=setup();assert.equal((get('grid').innerHTML.match(/class="track-card"/g)||[]).length,24);get('load-more').fire('click');assert.equal((get('grid').innerHTML.match(/class="track-card"/g)||[]).length,48);get('search').value='BTS';get('search').fire('input');assert((get('grid').innerHTML.match(/class="track-card"/g)||[]).length<=24)});
test('chart tab renders all ranks, keeps pending sources honest, and switches back',()=>{const {get,doc}=setup();const tab={dataset:{view:'chart'}};doc.fire('click',{target:{closest:s=>s==='button[data-view]'?tab:null}});assert.equal(get('chart-panel').hidden,false);assert.equal(get('library-panel').hidden,true);assert.equal((get('chart-tracks').innerHTML.match(/class="chart-track"/g)||[]).length,100);assert.match(get('chart-tracks').innerHTML,/待补舞蹈/);const home={dataset:{view:'library'}};doc.fire('click',{target:{closest:s=>s==='button[data-view]'?home:null}});assert.equal(get('library-panel').hidden,false)});
test('view navigation creates browser history while search replaces current entry',()=>{const {ctx,doc,get}=setup();for(const view of ['chart','playlists'])doc.fire('click',{target:{closest:s=>s==='button[data-view]'?{dataset:{view}}:null}});assert.equal(ctx.history.entries.length,2);assert.match(ctx.history.entries[0],/view=chart/);get('search').value='BTS';get('search').fire('input');assert.equal(get('library-panel').hidden,false);assert.equal(ctx.history.entries.length,3);assert.match(ctx.history.current,/q=BTS/)});
test('chart search uses order-independent tokens like the catalog',()=>{const {get,doc}=setup();doc.fire('click',{target:{closest:s=>s==='button[data-view]'?{dataset:{view:'chart'}}:null}});get('search').value='BTS SWIM';get('search').fire('input');assert.equal((get('chart-tracks').innerHTML.match(/class="chart-track"/g)||[]).length,1);assert.match(get('chart-tracks').innerHTML,/SWIM/)});

test('playlist quick selection preserves a back entry to the playlist',()=>{const {ctx,doc}=setup();doc.fire('click',{target:{closest:s=>s==='button[data-view]'?{dataset:{view:'playlists'}}:null}});const q={dataset:{query:'BTS Dynamite'},closest:()=>({})};doc.fire('click',{target:{closest:s=>s==='[data-query]'?q:null}});assert.equal(ctx.history.entries.length,2);assert.match(ctx.history.entries[0],/view=playlists/)});
test('external-only source does not promise a nonexistent embed or use another source cover',()=>{const {doc,get,E}=setup();for(const [filter,value] of [['platform','Vimeo'],['type','镜面']])doc.fire('click',{target:{closest:s=>s==='[data-filter]'?{dataset:{filter,value}}:null}});assert(!get('grid').innerHTML.includes('idle-queencard.jpg'));const t=new E();t.dataset={song:'idle-queencard'};doc.fire('click',{target:{closest:s=>s==='[data-song]'?t:null}});assert.match(get('song-detail').innerHTML,/此版本请前往原站观看/);assert(!get('song-detail').innerHTML.includes('点击下方「站内观看」'))});
test('active filter can be removed without opening advanced filters',()=>{const {doc,get}=setup();get('search').value='FREAK';get('search').fire('input');assert.match(get('active-filter').innerHTML,/data-remove-filter="query"/);doc.fire('click',{target:{closest:s=>s==='[data-remove-filter]'?{dataset:{removeFilter:'query'}}:null}});assert.equal(get('search').value,'');assert.equal(get('active-filter').hidden,true)});
test('sources have concise two-pane layout and expandable verification',()=>{const {doc,get,E}=setup();const t=new E();t.dataset={song:'yuqi-freak'};doc.fire('click',{target:{closest:s=>s==='[data-song]'?t:null}});assert.match(get('song-detail').innerHTML,/class="source-layout"/);assert.match(get('song-detail').innerHTML,/<details class="verification-details">/)});
